parameters:
- name: workingDirectory
  type: string
  default: $(Build.SourcesDirectory)/Web
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'
  workingDirectory: ${{ parameters.workingDirectory }}

- script: |
    npm run build
  displayName: 'npm build'
  workingDirectory: ${{ parameters.workingDirectory }}
  env:
    NODE_OPTIONS: --max_old_space_size=16384

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '${{ parameters.workingDirectory }}/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-web.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'webDrop' 
    